name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Set up test automation reporting
        uses: tesults/test-automation-reporting@v1
      - name: Run tests
        run: mvn --batch-mode test
