name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: pip
      - run: python -m pip install -r requirements.txt
      - name: Set up test automation reporting
        uses: tesults/test-automation-reporting@v1
      - name: Run tests
        run: python -m pytest
